apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: chaitraboggaram/k8s-key-value-store-redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
          readOnly: true
      volumes:
      - name: redis-config
        configMap:
          name: redis-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
