apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-value-store-api-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-value-store-api-worker
      component: key-value-store-api-worker
  template:
    metadata:
      labels:
        app: key-value-store-api-worker
        component: key-value-store-api-worker
    spec:
      containers:
      - name: key-value-store-worker
        image: abhilakshsinghreen/key-value-store-api-worker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: REDIS_HOST
          value: "redis-server-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: key-value-store-api-worker-service
spec:
  selector:
    app: key-value-store-api-worker
    component: key-value-store-api-worker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
