apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: key-value-store-api-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: key-value-store-api-worker
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25
